### ISSUE TITLE
HEIC [Unsupported]

### ISSUE THREAD

**Issue by ardalis** [DavidAnson/ConvertTo-Jpeg#10]
I installed this:
https://www.microsoft.com/en-us/p/heif-image-extensions/9pmmsr1cgpwg?activetab=pivot:reviewstab

But it still says my .HEIC photos are [Unsupported]. What should I do?

**Comment by DavidAnson** [comment]
I think you're missing one of the required extensions. Please have a look at: https://github.com/DavidAnson/ConvertTo-Jpeg#heicheif

A good test is to try to open a HEIC image in the stock Windows Photos app - until that works, the problem isn't with this script. :)

**Comment by ardalis** [comment]
Yeah, I read the README a bunch of times and installed the required software. Restarted machine, just to be sure. But still getting this:

![image](https://user-images.githubusercontent.com/782127/81475703-d1168200-91db-11ea-9d93-365132f39fc4.png)

**Comment by ardalis** [comment]
Interesting note. I just copied the file and script to my local drive and it works. Must be some network permission issue. That's a shame since the files I want to convert are all on my NAS drive.

**Comment by DavidAnson** [comment]
Wow, great troubleshooting! Did you happen to try mounting that network share as a drive (ex: “net use”)? Is that enough to get it working, or does it still not like the remote storage?

**Comment by ardalis** [comment]
Not yet; I may give that a try and let you know.
