### ISSUE TITLE
Can't Convert webp to jpg

### ISSUE THREAD

**Issue by ALittleOfEverything88** [DavidAnson/ConvertTo-Jpeg#14]
If I read the main page correctly, this script should be able to convert webp to jpg. When I run the command to do so, I get: 
"[Unsupported]"

Is there a way to convert webp to jpg with this script?

**Comment by DavidAnson** [comment]
If Windows can read the .webp image, this script should be able to convert it. An easy way to check is to double click the image - if it opens in the Photos viewer, that shows Windows can read the file.

**Comment by ALittleOfEverything88** [comment]
What if I don't have the photos viewer installed on my computer? Is that
required for the script to work? The file opens fine in Irfanview but if I
look at the file in explorer in thumbnail view I do not see a preview of
the file (like I would for a jpg file).

IMPORTANT:

By reading this email, you agree, on behalf of your employer and
associates, to release me from all obligations and waivers arising from any
and all non negotiated agreements, licenses, terms-of-service, shrinkwrap,
clickwrap, browsewrap, confidentiality, non-disclosure, non-compete and
acceptable use policies that I have entered into with your employer, its
partners, licensors, agents and assigns, in perpetuity, without prejudice
to my ongoing rights and privileges. You further represent that you have
the authority to release me from any such "agreements" on behalf of your
employer and relevant associates.

Please be aware that this message has, quite likely, been harvested and
possibly processed by the NSA, under §1881 FISAAA (now s702 FISA as
amended).
This email is intended for the use of the individual addressee(s) named
above and may contain information that is confidential privileged or
unsuitable for overly sensitive persons with low self-esteem, no sense of
humor or irrational religious beliefs.

If you are not the intended recipient, any dissemination, distribution or
copying of this email is not authorized (either explicitly or implicitly)
and constitutes an irritating social faux pas.

Unless the words absquatulation, witzelsucht, strikhedonia and
pneumonoultramicroscopicsilicovolcanoconiosis have been used in their
correct context somewhere other than in this warning, they do not have any
legal or grammatical use and may be ignored. No animals were harmed in the
transmission of this email. The cats treating my garden as Grand Toilet
Central, however, are courting a super soaker blasting.

Those of you with an overwhelming fear of the unknown will be gratified to
learn that there is no hidden message revealed by reading this warning
backwards, so just ignore that Alert Notice from Microsoft.

However, by pouring a complete circle of salt around yourself and your
computer you can ensure that no harm befalls you and your pets. If you have
received this email in error, please add some nutmeg and egg whites, whisk
and place in a warm oven for 40 minutes.
Thank you for your cooperation
---------

This email has been scanned by Edgar the Virus Hunter (Version .0001) (c)
1982
For more information please visit the Edgar the Virus Hunter Website
<http://www.homestarrunner.com/sbemail118.html>.

**Comment by DavidAnson** [comment]
Great! Can you link to the WEBP decoder, please? I can reference that from the README.

**Comment by ALittleOfEverything88** [comment]
Here you go!

<https://www.microsoft.com/en-us/p/webp-image-extensions/9pg2dk419drg#activetab=pivot:overviewtab>
https://www.microsoft.com/en-us/p/webp-image-extensions/9pg2dk419drg
<https://www.microsoft.com/en-us/p/webp-image-extensions/9pg2dk419drg#activetab=pivot:overviewtab>
