### ISSUE TITLE
Output file name extension not replaced.

### ISSUE THREAD

**Issue by zapwong** [DavidAnson/ConvertTo-Jpeg#18]
The script works fine. 
Output file name now look like filename.heic.jpg.

On changing line 91-92 to the followings will solve the issue. 

```
            $extension = $inputFile.FileType
            $outputFileName = $inputFile.Name -replace ($extension + "$"), `".jpg"`
```

**Comment by DavidAnson** [comment]
The current naming of the output file is deliberate because it shows the file has been converted.
