### ISSUE TITLE
Unsupported HEIC ?

### ISSUE THREAD

**Issue by daniel-tejeda-trimble** [DavidAnson/ConvertTo-Jpeg#20]
Hello, 
Thanks for this script, super helpful! I'm having issues with a set of files (one example attached). This is odd since I've been using it but not sure why its showing unsupported. Any help is appreciated. 

<img width="1010" alt="image" src="https://github.com/DavidAnson/ConvertTo-Jpeg/assets/104866339/58fb20c5-ea90-48b4-b4d5-924bd379a1b5">

[0F77B579199E4C0986570C26657A8AC9.zip](https://github.com/DavidAnson/ConvertTo-Jpeg/files/13398166/0F77B579199E4C0986570C26657A8AC9.zip)

Thanks!

**Comment by DavidAnson** [comment]
No idea, sorry! Since the basic scenario already works for you, we can probably rule out setup and codec install issues. My guess is that perhaps that file is partially corrupt or it may be that newer Apple devices produce HEIC files that the current Microsoft codec does not understand.

**Comment by matheusgomesms** [comment]
Same here, took some photos with latest iOS and at the moment, without much research, it shows the files as "Unsupported"

**Comment by daniel-tejeda-trimble** [comment]
> No idea, sorry! Since the basic scenario already works for you, we can probably rule out setup and codec install issues. My guess is that perhaps that file is partially corrupt or it may be that newer Apple devices produce HEIC files that the current Microsoft codec does not understand.

Thanks for your answer. I'm curious, If Microsoft codec doesn't understand the file how can I open it and see it ok in photos? This is set of photos taking with the same device and I get [Unsupported] for all of them. I think the "newer apple device" may be what's happening.

**Comment by DavidAnson** [comment]
I'm not sure. The way this script loads images is not specific to any codec and has not changed in many years.

**Comment by daniel-tejeda-trimble** [comment]
I found the issue writing the exception to the output. Not sure if its powershell or what but the fact that I had [] chars in the absolute path was the problem. Once I changed this, it works. 

<img width="1256" alt="image" src="https://github.com/DavidAnson/ConvertTo-Jpeg/assets/104866339/2f1dd804-ec9a-4ba9-9c87-8753916971a9">
