### ISSUE TITLE
Unsupported HEIC format

### ISSUE THREAD

**Issue by Emil113** [DavidAnson/ConvertTo-Jpeg#5]
Hi there, thanks for the script.  I tried to convert a few HEIC files with it but as it's running next to each heic file it says [Unsupported].  Here's what I tried:

```
PS C:\Users\User\Downloads> dir C:\Users\User\Downloads\ | .\ConvertTo-Jpeg.ps1
C:\Users\User\Downloads\58655742389__9F1B98B6-6B5D-4B00-87E8-C0999730B83D.jpg [Already JPEG]
C:\Users\User\Downloads\58655742389__9F1B98B6-6B5D-4B00-87E8-C0999730B83D.mov [Unsupported]
C:\Users\User\Downloads\ConvertTo-Jpeg.ps1 [Unsupported]
C:\Users\User\Downloads\IMG_2730.heic [Unsupported]
C:\Users\User\Downloads\IMG_2731.heic [Unsupported]
C:\Users\User\Downloads\IMG_2732.heic [Unsupported]
C:\Users\User\Downloads\IMG_2733.heic [Unsupported]
PS C:\Users\User\Downloads>
```

Any suggestions?

**Comment by DavidAnson** [comment]
It seems like the required codecs are not installed/working. More info here: https://github.com/DavidAnson/ConvertTo-Jpeg#heicheif

Try opening one of the HEIC files in Windows Explorer - if that fails, it is a codec issue.

**Comment by Emil113** [comment]
Thanks for the reply David.  I think that's the issue.  It wants me to pay for the codec first from the Microsoft store.  Was trying to avoid that but I'll get it if I have to.

**Comment by Emil113** [comment]
Thanks for the reply David.  I think that's the issue.  It wants me to pay for the codec first from the Microsoft store.  Was trying to avoid that but I'll get it if I have to.
