### ISSUE TITLE
Skip existing files

### ISSUE THREAD

**Issue by BergenSoft** [DavidAnson/ConvertTo-Jpeg#6]
Is it possible to skip existing files?
If the files **a.heic** and **a.heic.jpg** exists, than do not make any checks nor conversions?

**Comment by DavidAnson** [comment]
You could filter the list of files passed to this script through the pipeline to remove those cases. As a matter of personal preference, the script will regenerate output files every time, but it would not be a big deal to add an option to skip such cases.

**Comment by BergenSoft** [comment]
I tried a bit and finally I got this script:

`Function Filter-Existing {
	[CmdletBinding()]
    Param(
		[Parameter(ValueFromPipelineByPropertyName)] $FullName
	)

	process
	{
		if (!(Test-Path "$FullName.jpg"))
		{
			return $FullName
		}
	}
}

Get-ChildItem "PATH_GOES_HERE" -Include *.heic -Recurse | Filter-Existing | .\ConvertTo-Jpeg.ps1`

Maybe someone else can also use it or even improve it.
