### ISSUE TITLE
Access Denied error

### ISSUE THREAD

**Issue by JasonThePirate** [DavidAnson/ConvertTo-Jpeg#7]
I've successfully used this on my last Windows 10 PC, but am trying to use it with my newer Windows 10 PC. I installed both the _HEVC Video Extensions from Device Manufacturer_ and _HEIF Image Extensions_. I downloaded the latest copy of this script. I am now however getting an error:

PS C:\Users\Jason\Documents\Programming\Windows Scripts> .\ConvertTo-Jpeg.ps1 -Files F:\2019\process\IMG_1669.HEIC
F:\2019\process\IMG_1669.HEICSystem.Management.Automation.MethodInvocationException: Exception calling "Wait" with "0" argument(s): "One or more errors occurred." ---> System.AggregateExcepti
on: One or more errors 
occurred.

**Comment by DavidAnson** [comment]
The title of the issue says “access denied“, but I don’t see that in the details. Could you please include the entire output when this fails? Is there a chance that the disk is full or unwriteable, perhaps?

**Comment by JasonThePirate** [comment]
Thanks for the quick response!

Here's the full message I'm receiving. The access denied message is the
fourth line down. Using PS I can Copy-Item to write new files:

PS C:\users\Jason\Documents\Programming\Windows Scripts>
> .\ConvertTo-Jpeg.ps1 F:\2019\process\IMG_1669.HEIC
> F:\2019\process\IMG_1669.HEICSystem.Management.Automation.MethodInvocationException:
> Exception calling "Wait" with "0" argument(s): "One or more
> errors occurred." ---> System.AggregateException: One or more errors
> occurred. --->
> System.UnauthorizedAccessException: Access is denied. (Exception from
> HRESULT: 0x80070005 (E_ACCESSDENIED))
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
> includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,
> CancellationToken cancellationToken)
>    at CallSite.Target(Closure , CallSite , Object )
>    --- End of inner exception stack trace ---
>    at
> System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
> funcContext, Exception
> exception)
>    at
> System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
> frame)
>    at
> System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
> frame)
>    at
> System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
> frame)
> At C:\users\Jason\Documents\Programming\Windows
> Scripts\ConvertTo-Jpeg.ps1:104 char:13
> +             throw $_.Exception.ToString()
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped:
> (System.Manageme...tedFrame frame):String) [], RuntimeException
>     + FullyQualifiedErrorId :
> System.Management.Automation.MethodInvocationException: Exception calling
> "Wait" with "0
>    " argument(s): "One or more errors occurred." --->
> System.AggregateException: One or more errors occurred. ---> Sy
>   stem.UnauthorizedAccessException: Access is denied. (Exception from
> HRESULT: 0x80070005 (E_ACCESSDENIED))
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
> includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,
> CancellationToken cancellationToken)
>    at CallSite.Target(Closure , CallSite , Object )
>    --- End of inner exception stack trace ---
>        at
> System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
> funcContext, Excepti
>    on exception)
>    at
> System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
> frame)
>    at
> System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
> frame)
>    at
> System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
> frame)

**Comment by DavidAnson** [comment]
Sorry, I’m not sure what’s going on and the output only confirms what you said about it being an access violation. What I’d probably suggest next is to add a bunch of simple logging statements to the script in order to figure out which line specifically is failing. Perhaps that will help uncover the issue?

**Comment by JasonThePirate** [comment]
Seems to happen when line 87
>
> $bitmap = AwaitOperation ($decoder.GetSoftwareBitmapAsync())
> ([Windows.Graphics.Imaging.SoftwareBitmap])


is running through the AwaitOperation function and hits line 32

> $netTask.Wait() | Out-Null




>

**Comment by DavidAnson** [comment]
Any chance the image is corrupt? Can you open and view it in Windows Photo viewer?

**Comment by JasonThePirate** [comment]
I just checked and the file is good and will open with Photos.

**Comment by DavidAnson** [comment]
Can you confirm the same file converts okay on your other machine?

**Comment by Billtard** [comment]
I'm having the same issue. 
`PS C:\temp\iphone_pics> ..\heicToJpegConverter.ps1 .\IMG_0258.HEIC
.\IMG_0258.HEICSystem.Management.Automation.MethodInvocationException: Exception calling "Wait" with "0" 
argument(s): 
"One or more errors occurred." ---> System.AggregateException: One or more errors occurred. ---> 
System.Exception: No suitable transform was found to encode or decode the content. (Exception from 
HRESULT: 0xC00D5212)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
frame)
At C:\temp\heicToJpegConverter.ps1:107 char:13
+             throw $_.Exception.ToString()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (System.Manageme...tedFrame frame):String) [], RuntimeE 
   xception
    + FullyQualifiedErrorId : System.Management.Automation.MethodInvocationException: Exception calling 
    "Wait" with "0" argument(s): "One or more errors occurred." ---> System.AggregateException: One or  
   more errors occurred. ---> System.Exception: No suitable transform was found to encode or decode t   
 he content. (Exception from HRESULT: 0xC00D5212)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationTok 
   en)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
       at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcC 
   ontext, Exception exception)
       at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)  
  
       at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
    frame)
       at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
    frame)
 `

**Comment by DavidAnson** [comment]
As above, please share or link to a file I can use to reproduce the issue. I’m happy to look into this, but the output above isn’t distinguishable to me from a configuration issue.
