### ISSUE TITLE
Add link to free version of HEVC Video Extensions in Store

### ISSUE THREAD

**Issue by lgmorand** [DavidAnson/ConvertTo-Jpeg#8]
The same HEIC extension can be bought on the store for 1€ or for free. the link to the free version is here:
https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot%3aoverviewtab

could be added as alternate link in the readme ;)

**Comment by DavidAnson** [comment]
Visiting that link shows me "HEVC Video Extensions from Device Manufacturer is currently not available.". I think this may have been sponsored by your computer manufacturer or something and is not broadly available.
