### ISSUE TITLE
Renaming incorrect

### ISSUE THREAD

**Issue by lgmorand** [DavidAnson/ConvertTo-Jpeg#9]
IMG_1234.HEIC -> IMG_1234.**HEIC**.jpg

Is it normal that the extension .heic is kept ? why not replace it directly if we reencode the format ? or maybe a parameter to have this possibility and alter the line 90 ? What do you think ?

**Comment by DavidAnson** [comment]
This is deliberate so it’s clear where the image content came from. I think it’s also less likely to conflict with an existing file name. It could be added as an option, but it’s also easy to bulk rename “*.HEIC.jpg” after converting.
